CC=criscasm

all: branchA factorial stacktest truthmachine syscall

branchA:
	$(CC) branchA.asm

factorial:
	$(CC) factorial.asm

stacktest:
	$(CC) stacktest.asm

truthmachine:
	$(CC) truthmachine.asm

syscall:
	$(CC) syscall.asm

clean:
	rm *.bin
